import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useReducer } from "react";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push("/Login");
  }, []);
  return (
    <>
      <Head>
        <title>Automated Bill Processing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
